server:
  port: 8710
spring:
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: 5672
    username: provider
    password: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql_host:localhost}:3306/tcc_account?useSSL=false&useAffectedRows=true
    username: root
    password: root
    continue-on-error: false
    tomcat:
      max-active: 50
      initial-size: 20
      min-idle: 6
      #      记录abandoned信息
      log-abandoned: true
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      test-while-idle: true
      test-on-borrow: false
      test-on-connect: false
      test-on-return: false
      validation-query: "select 'x' "
      validation-query-timeout: 1
      log-validation-errors: true
      time-between-eviction-runs-millis: 30000
      num-tests-per-eviction-run: 20
      max-idle: 20
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8

mybatis:
  check-config-location: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
