server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
  port: 9527
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #与注册服务关联
