server:
  port: 8707
  undertow:
    io-threads: 8
    worker-threads: 156
    buffer-size: 1024
    direct-buffers: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql_host:localhost}:3306/hmily-stock?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: admin
    data: classpath:data.sql
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto : none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect

org:
  dromara:
    hmily:
      serializer: kryo
      recoverDelayTime: 128
      retryMax: 30
      scheduledDelay: 128
      scheduledThreadMax: 10
      repositorySupport: redis
      started: true
      hmilyRedisConfig:
        password: redis123
        hostname: 127.0.0.1
        port: 6379
