spring:
  application:
    name: consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://center-8701:8701/eureka/,http://center-8702:8702/eureka/,http://center-8703:8703/eureka/,
server:
  port: 8722
feign:
  hystrix:
    enabled: true
logging:
  path: E:\\log\\root\\
