spring:
  application:
    name: zuul
server:
  port: 8730
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: provider
    consumer:
      path: /consumer/**
      serviceId: consumer
management:
  security:
    enabled: false
logging:
  path: E:\\log\\root\\
---
spring:
  application:
    name: zuul
server:
  port: 8731
eureka:
  client:
    serviceUrl:
      defaultZone: http://center-8701:8701/eureka/,http://center-8702:8702/eureka/,http://center-8703:8703/eureka/,
zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: provider
    consumer:
      path: /consumer/**
      serviceId: consumer
management:
  security:
    enabled: false
logging:
  path: E:\\log\\root\\
---
spring:
  application:
    name: zuul
server:
  port: 8732
eureka:
  client:
    serviceUrl:
      defaultZone: http://center-8701:8701/eureka/,http://center-8702:8702/eureka/,http://center-8703:8703/eureka/,
zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: provider
    consumer:
      path: /consumer/**
      serviceId: consumer
management:
  security:
    enabled: false
logging:
  path: E:\\log\\root\\
---
spring:
  application:
    name: zuul
server:
  port: 8733
eureka:
  client:
    serviceUrl:
      defaultZone: http://center-8701:8701/eureka/,http://center-8702:8702/eureka/,http://center-8703:8703/eureka/,
zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: provider
    consumer:
      path: /consumer/**
      serviceId: consumer
management:
  security:
    enabled: false
logging:
  path: E:\\log\\root\\