server:
  port: 8710
spring:
  application:
    name: provider
  rabbitmq:
    host: 192.168.0.154
    port: 5672
    username: provider
    password: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql_hostname:192.168.0.154}:3306/integral?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
mybatis-plus:
  checkConfigLocation: true
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑删除
      logic-not-delete-value: 0 #逻辑未删除