spring:
  application:
    name: provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
server:
  port: 8710
management:
  security:
    enabled: false
logging:
  path: E:\\log\\root\\
