spring:
  application:
    name: turbine
  rabbitmq:
    host: 192.168.0.154
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
server:
  port: 8750
management:
  security:
    enabled: false
logging:
  path: E:\\log\\root\\
#turbine:
#  app-config: consumer