spring:
  application:
    name: center
  profiles:
    active: 8702
server:
  port: 8702
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://center-8701:8701/eureka,http://center-8703:8703/eureka
    fetch-registry: true
  instance:
    hostname: center-8702
logging:
  path: E:\\log\\root\\