spring:
  application:
    name: center
server:
  port: 8700
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8700/eureka
    fetch-registry: false
  instance:
    hostname: localhost
logging:
  path: E:\\log\\root\\