spring:
  application:
    name: center
  profiles:
    active: 8701
server:
  port: 8701
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://center-8702:8702/eureka,http://center-8703:8703/eureka
    fetch-registry: true
  instance:
    hostname: center-8701
logging:
  path: E:\\log\\root\\