datasource:
  name: sys_admin
server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
  port: 8088
spring:
  profiles:
    include:
      - mybatisPlus
      - redis
      - database
  application:
    name: admin
logging:
  file:
    path: ${LOGGING_FILE_PATH}


