server:
  port: 8706
  undertow:
    buffer-size: 1024
    direct-buffers: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql_host:localhost}:3306/account?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: admin
    schema: classpath:schema.sql
    initialization-mode: never
    data: classpath:data.sql
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto : validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  cloud:
    alibaba:
      seata:
        tx-service-group: seata-account-service-group
#seata:
#  enabled: true
#  application-id: applicationName
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  use-jdk-proxy: false
#  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
#  client:
#    rm:
#      async-commit-buffer-limit: 1000
#      report-retry-count: 5
#      table-meta-check-enable: false
#      report-success-enable: false
#      saga-branch-register-enable: false
#      lock:
#        retry-interval: 10
#        retry-times: 30
#        retry-policy-branch-rollback-on-conflict: true
#    tm:
#      commit-retry-count: 5
#      rollback-retry-count: 5
#    undo:
#      data-validation: true
#      log-serialization: jackson
#      log-table: undo_log
#    log:
#      exceptionRate: 100
#  service:
#    vgroup-mapping:
#      my_test_tx_group: default
#    grouplist:
#      default: 127.0.0.1:8091
#    enable-degrade: false
#    disable-global-transaction: false
#  transport:
#    shutdown:
#      wait: 3
#    thread-factory:
#      boss-thread-prefix: NettyBoss
#      worker-thread-prefix: NettyServerNIOWorker
#      server-executor-thread-prefix: NettyServerBizHandler
#      share-boss-worker: false
#      client-selector-thread-prefix: NettyClientSelector
#      client-selector-thread-size: 1
#      client-worker-thread-prefix: NettyClientWorkerThread
#      worker-thread-size: default
#      boss-thread-size: 1
#    type: TCP
#    server: NIO
#    heartbeat: true
#    serialization: seata
#    compressor: none
#    enable-client-batch-send-request: true
#  config:
#    type: file
#    consul:
#      server-addr: 127.0.0.1:8500
#    apollo:
#      apollo-meta: http://192.168.1.204:8801
#      app-id: seata-server
#      namespace: application
#    etcd3:
#      server-addr: http://localhost:2379
#    nacos:
#      namespace:
#      serverAddr: localhost
#      group: SEATA_GROUP
#      userName: ""
#      password: ""
#    zk:
#      server-addr: 127.0.0.1:2181
#      session-timeout: 6000
#      connect-timeout: 2000
#      username: ""
#      password: ""
#  registry:
#    type: file
#    consul:
#      server-addr: 127.0.0.1:8500
#    etcd3:
#      serverAddr: http://localhost:2379
#    eureka:
#      weight: 1
#      service-url: http://localhost:8761/eureka
#    nacos:
#      application: seata-server
#      server-addr: localhost
#      namespace:
#      userName: ""
#      password: ""
#    redis:
#      server-addr: localhost:6379
#      db: 0
#      password:
#      timeout: 0
#    sofa:
#      server-addr: 127.0.0.1:9603
#      region: DEFAULT_ZONE
#      datacenter: DefaultDataCenter
#      group: SEATA_GROUP
#      addressWaitTime: 3000
#      application: default
#    zk:
#      server-addr: 127.0.0.1:2181
#      session-timeout: 6000
#      connect-timeout: 2000
#      username: ""
#      password: ""
