datasource:
  name: area
server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
spring:
  profiles:
    include:
      - redis
      - mysql
  application:
    name: area
logging:
  file:
    path: ${LOGGING_FILE_PATH}


