server:
  port: 8705
  undertow:
    io-threads: 8
    worker-threads: 156
    buffer-size: 1024
    direct-buffers: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql_host:localhost}:3306/tcc_order?useSSL=false&useAffectedRows=true
    username: root
    password: root
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
mybatis:
  check-config-location: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
org:
  dromara:
    hmily:
      serializer: kryo
      recoverDelayTime: 128
      retryMax: 30
      scheduledDelay: 128
      scheduledThreadMax: 10
      repositorySupport: redis
      started: true
      hmilyRedisConfig:
        password: redis123
        hostname: 127.0.0.1
        port: 6379
