server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
spring:
  profiles:
    include:
      - redis
      - mysql
  application:
    name: hero
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


