server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql_host:localhost}:3306/order?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: admin
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
  cloud:
    alibaba:
      seata:
        tx-service-group: seata-order-service-group
  profiles:
    include: mybatisPlus