seata:
  registry:
    type: nacos
    nacos:
      application: ${sping.application.name}
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      namespace: ""
      username: "nacos"
      password: "nacos"
