#wx:
#  mp:
#    app-id: wx1f8914e4e7cd1805
#    secret: 1c9eb67abb53f8f934501af1866ec1fd
#    token: MP200722
#    aes-key: 7IC4ZoSimhSFJdKA0QyG8RDs9kSLYa5CSRobUnuhWXT
#    config-storage:
#      type: redistemplate
#      key-prefix: wx
wx:
  mp:
    configs:
      - appId: wx1f8914e4e7cd1805 # 第一个公众号的appid
        secret: 1c9eb67abb53f8f934501af1866ec1fd # 公众号的appsecret
        token: MP200722 # 接口配置里的Token值
        aesKey: 7IC4ZoSimhSFJdKA0QyG8RDs9kSLYa5CSRobUnuhWXT # 接口配置里的EncodingAESKey值
#      - appId: 2222 # 第二个公众号的appid，以下同上
#        secret: 1111
#        token: 111
#        aesKey: 111
